#source 'https://github.com/CocoaPods/Specs.git'
platform:ios,'8.0'
target "CGXVerticalMenuView-OC" do

pod 'CGXVerticalMenuView-OC', :path => '../'

pod 'MJRefresh'
pod 'SDWebImage'
pod 'MJExtension'
pod 'Masonry'

end
